--------------------------------------------------------
--  파일이 생성됨 - 일요일-12월-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "BOOK" 
   (	"B_CODE" VARCHAR2(20 BYTE), 
	"B_TITLE" VARCHAR2(50 BYTE), 
	"B_NAME" VARCHAR2(50 BYTE), 
	"B_PUBLISHING" VARCHAR2(50 BYTE), 
	"B_DATE" DATE, 
	"B_PRICE" NUMBER, 
	"B_LENT" VARCHAR2(20 BYTE), 
	"B_LENT_NUM" NUMBER, 
	"B_LENT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "MEMBER" 
   (	"M_ID" VARCHAR2(20 BYTE), 
	"M_NAME" VARCHAR2(50 BYTE), 
	"M_PHONE" VARCHAR2(20 BYTE), 
	"M_ADDRESS" VARCHAR2(50 BYTE), 
	"M_SEX" VARCHAR2(10 BYTE), 
	"M_DATE" DATE, 
	"M_LENT" NUMBER, 
	"M_TOTAL_LENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PHONE
--------------------------------------------------------

  CREATE TABLE "PHONE" 
   (	"ID" NUMBER, 
	"PNAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BOOK
SET DEFINE OFF;
Insert into BOOK (B_CODE,B_TITLE,B_NAME,B_PUBLISHING,B_DATE,B_PRICE,B_LENT,B_LENT_NUM,B_LENT_DATE) values ('111','삼국지','나관중','문학사',to_date('15/01/15','RR/MM/DD'),2000,'hong',6,to_date('21/12/05','RR/MM/DD'));
Insert into BOOK (B_CODE,B_TITLE,B_NAME,B_PUBLISHING,B_DATE,B_PRICE,B_LENT,B_LENT_NUM,B_LENT_DATE) values ('222','서유기','오승은','중국사',to_date('14/08/20','RR/MM/DD'),30000,'hong',3,to_date('21/12/04','RR/MM/DD'));
Insert into BOOK (B_CODE,B_TITLE,B_NAME,B_PUBLISHING,B_DATE,B_PRICE,B_LENT,B_LENT_NUM,B_LENT_DATE) values ('333','햄릿','셰익스피어','고전사',to_date('13/09/17','RR/MM/DD'),25870,null,3,null);
Insert into BOOK (B_CODE,B_TITLE,B_NAME,B_PUBLISHING,B_DATE,B_PRICE,B_LENT,B_LENT_NUM,B_LENT_DATE) values ('444','국가','플라톤','철학과생각',to_date('10/11/14','RR/MM/DD'),20000,'hong',3,to_date('21/12/04','RR/MM/DD'));
REM INSERTING into MEMBER
SET DEFINE OFF;
Insert into MEMBER (M_ID,M_NAME,M_PHONE,M_ADDRESS,M_SEX,M_DATE,M_LENT,M_TOTAL_LENT) values ('hong','장윈터','010-111-1111','경기도 부천시','여자',to_date('19/09/17','RR/MM/DD'),3,12);
Insert into MEMBER (M_ID,M_NAME,M_PHONE,M_ADDRESS,M_SEX,M_DATE,M_LENT,M_TOTAL_LENT) values ('lee','이터시','010-222-2222','서울 마포구','남자',to_date('19/10/23','RR/MM/DD'),0,1);
Insert into MEMBER (M_ID,M_NAME,M_PHONE,M_ADDRESS,M_SEX,M_DATE,M_LENT,M_TOTAL_LENT) values ('park','장도터','010-333-3333','경기도 안양시','여자',to_date('19/11/17','RR/MM/DD'),0,0);
Insert into MEMBER (M_ID,M_NAME,M_PHONE,M_ADDRESS,M_SEX,M_DATE,M_LENT,M_TOTAL_LENT) values ('kim','카터나','010-444-4444','서울 동작구','여자',to_date('20/02/20','RR/MM/DD'),0,2);
REM INSERTING into PHONE
SET DEFINE OFF;
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (10,'이민','010-999-999','99@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (1,'장윈터','010-111-1111','111@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (2,'이터시','010-222-2222','222@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (3,'장도터','010-333-3333','333@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (4,'카터나','010-444-4444','444@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (5,'전한터','010-555-5555','555@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (6,'이터경','010-666-6666','666@bc.ac.kr');
Insert into PHONE (ID,PNAME,PHONE,EMAIL) values (7,'이민터','010-777-7777','777@bc.ac.kr');
--------------------------------------------------------
--  DDL for Index PHONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PHONE_PK" ON "PHONE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007066
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007066" ON "BOOK" ("B_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007067
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007067" ON "MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007066
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007066" ON "BOOK" ("B_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007067
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007067" ON "MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PHONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PHONE_PK" ON "PHONE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "BOOK" ADD PRIMARY KEY ("B_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" ADD PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHONE
--------------------------------------------------------

  ALTER TABLE "PHONE" ADD CONSTRAINT "PHONE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PHONE" MODIFY ("ID" NOT NULL ENABLE);
